version: '2.4'

services:
  ipify:
    image: owlab/ipify
    expose:
      - 3000
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.10
      public1:
        ipv4_address: 172.31.0.10

  broker:
    image: nats
    expose:
      - 4222
      - 8222
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.30
      public1:
        ipv4_address: 172.31.0.30

  db:
    image: percona:5.7
    cap_add:
      - NET_ADMIN
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myst_api
      MYSQL_USER: myst_api
      MYSQL_PASSWORD: myst_api
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.201
      public1:
        ipv4_address: 172.31.0.201


  #private blockchain
  ganache:
    image: trufflesuite/ganache-cli:v6.6.0-beta.0
    ports:
      - 8545:8545
    expose:
      - 8545
    command: >
      --mnemonic "amused glory pen avocado toilet dragon entry kitchen cliff retreat canyon danger"
    dns: 172.30.0.254
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    networks:
      public0:
        ipv4_address: 172.30.0.202
      public1:
        ipv4_address: 172.31.0.202

  transactor:
    image: mysteriumnetwork/transactor:latest
    environment:
      PORT: 8888
    expose:
      - 8888
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    depends_on:
      - ganache
    command: >
      -mystSCAddress 0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      -rpcEndpoint ws://ganache:8545
      -registry 0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      -ourIdentity 0x354bd098b4ef8c9e70b7f21be2d455df559705d7
      -balanceCheckInterval 1s
    volumes:
      - "../../bin/localnet/deployer/keystore:/keystore"
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.203
      public1:
        ipv4_address: 172.31.0.203

  mysterium-api:
    image: mysteriumnetwork/mysterium-api:0.5.22
    expose:
      - 80
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.default.rp_filter=0
      - net.ipv4.conf.all.rp_filter=0
      - net.ipv4.conf.eth0.rp_filter=0
      - net.ipv4.conf.eth1.rp_filter=0
    environment:
      APP_PORT: 80
      DB_HOST: db
      DB_NAME: myst_api
      DB_USER: myst_api
      DB_PASSWORD: myst_api
      ETHER_RPC_URL: "http://ganache:8545"
      IDENTITY_CONTRACT: "0x1955141ba8e77a5B56efBa8522034352c94f77Ea"
      ETHER_MINING_MODE: "poa"
      DISCOVERY_VERIFY_IDENTITY: "false"
    depends_on:
      - db
      - ganache
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.200
      public1:
        ipv4_address: 172.31.0.200

  router:
    build:
      context: ../..
      dockerfile: e2e/docker/forwarder/Dockerfile
    cap_add:
      - NET_ADMIN
    environment:
      - EXT_NAT=172.30.0.1
    networks:
      public0:
        ipv4_address: 172.30.0.254
      public1:
        ipv4_address: 172.31.0.254

  forwarder:
    build:
      context: ../..
      dockerfile: e2e/docker/forwarder/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - router
    environment:
      - GATEWAY=172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.2
      priv1:
        ipv4_address: 10.100.1.2

  forwarder2:
    build:
      context: ../..
      dockerfile: e2e/docker/forwarder/Dockerfile
    cap_add:
      - NET_ADMIN
    depends_on:
      - router
    environment:
      - GATEWAY=172.31.0.254
    dns: 172.31.0.254
    networks:
      public1:
        ipv4_address: 172.31.0.2
      priv0:
        ipv4_address: 10.100.0.2

  myst-consumer:
    build:
      context: ../..
      dockerfile: bin/docker/alpine/Dockerfile
    environment:
      - DEFAULT_ROUTE=10.100.1.2
    depends_on:
      - forwarder
    cap_add:
      - NET_ADMIN
    expose:
      - 4050
    command: >
      --ip-detector=http://ipify:3000/?format=json
      --api.address=http://mysterium-api/v1
      --ether.client.rpc=ws://ganache:8545
      --experiment-identity-check=true
      --ether.contract.payments=0x1955141ba8e77a5B56efBa8522034352c94f77Ea
      --keystore.lightweight
      --transactor.channel-implementation=0x599d43715DF3070f83355D9D90AE62c159E62A75
      --transactor.registry-address=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --accountant.accountant-id=0xf2e2c77D2e7207d8341106E6EfA469d1940FD0d8
      --accountant.address=http://accountant:8889/api/v1
      --transactor.address=http://transactor:8888/api/v1
      --ether.contract.payments=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      daemon
    dns: 172.30.0.254
    networks:
      priv1:
        ipv4_address: 10.100.1.101

  accountant:
    image: mysteriumnetwork/accountant:latest
    environment:
      PORT: 8889
    expose:
      - 8889
    depends_on:
      - ganache
    command: >
      -identityPassphrase ""
      -myst 0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      -rpcEndpoint ws://ganache:8545
      -registry 0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      -operator 0x354bd098b4ef8c9e70b7f21be2d455df559705d7
      -chImplementation 0x599d43715DF3070f83355D9D90AE62c159E62A75
      -keystoreDir /keystore
      -accountantAddress 0x241F6e1d0bB17f45767DC60A6Bd3D21Cdb543a0c
    volumes:
      - "./../bin/localnet/deployer/keystore:/keystore"

  myst-provider:
    build:
      context: ../..
      dockerfile: bin/docker/alpine/Dockerfile
    environment:
      - DEFAULT_ROUTE=10.100.0.2
    depends_on:
      - forwarder2
    cap_add:
      - NET_ADMIN
    expose:
      - 1194
      - 4050
    volumes:
      - ../../e2e/myst-provider/keystore:/var/lib/mysterium-node/keystore
    command: >
      --ip-detector=http://ipify:3000/?format=json
      --location.type=manual
      --location.country=e2e-land
      --experiment-identity-check=true
      --broker-address=broker
      --api.address=http://mysterium-api/v1
      --ether.client.rpc=ws://ganache:8545
      --transactor.registry-address=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --accountant.accountant-id=0xf2e2c77D2e7207d8341106E6EfA469d1940FD0d8
      --accountant.address=http://accountant:8889/api/v1
      --transactor.channel-implementation=0x599d43715DF3070f83355D9D90AE62c159E62A75
      --transactor.address=http://transactor:8888/api/v1
      --ether.contract.payments=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --keystore.lightweight
      service openvpn
      --agreed-terms-and-conditions
      --identity=0xd1a23227bd5ad77f36ba62badcb78a410a1db6c5
      --identity.passphrase=localprovider
      --openvpn.port=3000
    dns: 172.31.0.254
    networks:
      priv0:
        ipv4_address: 10.100.0.102

  go-runner:
    image: golang:1.13
    volumes:
      - $GOPATH:/go
    working_dir: /go/src/github.com/mysteriumnetwork/node
    dns: 172.30.0.254
    networks:
      public0:
        ipv4_address: 172.30.0.222
      public1:
        ipv4_address: 172.31.0.222
      priv0:
        ipv4_address: 10.100.0.222
      priv1:
        ipv4_address: 10.100.1.222

networks:
  public0:
    driver: "bridge"
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24
  public1:
    driver: "bridge"
    ipam:
      config:
        - subnet: 172.31.0.0/24
  priv0:
    driver: "bridge"
    ipam:
      config:
        - subnet: 10.100.0.0/24
  priv1:
    driver: "bridge"
    ipam:
      config:
        - subnet: 10.100.1.0/24
