version: '3'
services:

  broker:
    image: nats
    expose:
      - 4222
      - 8222

  #infrastructure - centralized api and db
  db:
    image: percona:5.7
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myst_api
      MYSQL_USER: myst_api
      MYSQL_PASSWORD: myst_api

  discovery:
    image: mysteriumnetwork/mysterium-api:0.2.2
    expose:
    - 80
    environment:
      APP_PORT: 80
      DB_HOST: db
      DB_NAME: myst_api
      DB_USER: myst_api
      DB_PASSWORD: myst_api
      ETHER_RPC_URL: "http://geth:8545"
      IDENTITY_CONTRACT: "0x1955141ba8e77a5B56efBa8522034352c94f77Ea"
      ETHER_MINING_MODE: "poa"
    depends_on:
    - db
    - geth

  #private blockchain with single miner and single node
  geth:
    image: mysteriumnetwork/geth:1.8.12
    expose:
      - 8545
    volumes:
      - geth-runtime:/ethereum/geth-runtime
      - ./geth/genesis.json:/ethereum/genesis.json
      - ./geth/keystore:/ethereum/keystore
      - ./geth/node_acc_password.txt:/ethereum/node_acc_password.txt
    command: >
      --syncmode 'full'
      --port 30311
      --rpc
      --rpcaddr '0.0.0.0'
      --rpcport 8545
      --rpcapi personal,db,eth,net,web3,txpool,miner
      --networkid 69
      --gasprice '1'
      --unlock '0xd9786b6ee6caf5cd0ef88301fc40de83bfac5594'
      --password node_acc_password.txt
      --rpcvhosts *
      --rpccorsdomain *
      --mine

  #go runner to run go programs inside localnet (usefull for contract deployment or e2e test running)
  go-runner:
    image: golang:1.10
    volumes:
      - $GOPATH:/go
    working_dir: /go/src/github.com/mysteriumnetwork/node

volumes:
  geth-runtime:
