version: '3'
services:

  #'external' IP detection
  ipify:
    image: owlab/ipify
    expose:
    - 3000

  myst-provider-0.5:
    image: mysteriumnetwork/myst:0.5
    depends_on:
      - broker
      - mysterium-api
      - ipify
    cap_add:
      - NET_ADMIN
    expose:
      - 1194
      - 4050
    volumes:
      - ../../e2e/myst-provider:/var/lib/mysterium-node
    command: >
      --ipify-url=http://ipify:3000
      --location.country=e2e-land
      --location.type=manual
      --experiment-promise-check
      --localnet
      --broker-address=broker
      --api.address=http://mysterium-api/v1
      --ether.client.rpc=http://ganache:8545
      service
      --agreed-terms-and-conditions
      --identity=0xd1a23227bd5ad77f36ba62badcb78a410a1db6c5
      --identity.passphrase=localprovider
      --openvpn.port=3000
      --payments.mystscaddress=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      openvpn,noop,wireguard

  myst-consumer-0.5:
    image: mysteriumnetwork/myst:0.5
    depends_on:
      - broker
      - mysterium-api
      - ipify
    cap_add:
      - NET_ADMIN
    expose:
      - 4050
    command: >
      --ip-detector=http://ipify:3000
      --experiment-promise-check
      --localnet
      --payments.mystscaddress=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      --api.address=http://mysterium-api/v1
      --broker-address=http://mysterium-api/v1
      --ether.client.rpc=http://ganache:8545
      daemon

  myst-provider-local:
    build:
      context: ../..
      dockerfile: bin/docker/alpine/Dockerfile
    depends_on:
      - broker
      - mysterium-api
      - ipify
      - transactor
    cap_add:
      - NET_ADMIN
    expose:
      - 1194
      - 4050
    volumes:
      - ../../e2e/myst-provider:/var/lib/mysterium-node
    command: >
      --ip-detector=http://ipify:3000
      --location.type=manual
      --location.country=e2e-land
      --localnet
      --firewall.protected.networks=""
      --broker-address=broker
      --api.address=http://mysterium-api/v1
      --ether.client.rpc=ws://ganache:8545
      --transactor.registry-address=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --accountant.accountant-id=0x676b9a084aC11CEeF680AF6FFbE99b24106F47e7
      --transactor.address=http://transactor:8888/api/v1
      service
      --agreed-terms-and-conditions
      --identity=0xd1a23227bd5ad77f36ba62badcb78a410a1db6c5
      --identity.passphrase=localprovider
      --openvpn.port=3000
      --payments.mystscaddress=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      openvpn,noop,wireguard


  myst-consumer-local:
    build:
      context: ../..
      dockerfile: bin/docker/alpine/Dockerfile
    depends_on:
      - broker
      - mysterium-api
      - ipify
      - transactor
    cap_add:
      - NET_ADMIN
    expose:
      - 4050
    command: >
      --ip-detector=http://ipify:3000
      --localnet
      --ether.client.rpc=ws://ganache:8545
      --api.address=http://mysterium-api/v1
      --keystore.lightweight
      --payments.mystscaddress=0x4D1d104AbD4F4351a0c51bE1e9CA0750BbCa1665
      --transactor.registry-address=0xbe180c8CA53F280C7BE8669596fF7939d933AA10
      --accountant.accountant-id=0x676b9a084aC11CEeF680AF6FFbE99b24106F47e7
      --transactor.address=http://transactor:8888/api/v1
      daemon
